### ISSUE TITLE
mag issue

### ISSUE THREAD

**Issue by IM02** [Mkalo/macro-maker#1]
[08:31:51.063] Failed to update the following module files:
 - index.js
 - ERROR: https://raw.githubusercontent.com/Mkalo/macro-maker/master/index.js
Downloaded file doesn't match hash specified in patch manifest! Possible causes:
   + Incorrect manifest specified by developer
   + NoPing (if you're using it) has a bug that can fuck up the download
 - README.md
 - ERROR: https://raw.githubusercontent.com/Mkalo/macro-maker/master/README.md
Downloaded file doesn't match hash specified in patch manifest! Possible causes:
   + Incorrect manifest specified by developer
   + NoPing (if you're using it) has a bug that can fuck up the download
 - Matt.js
 - ERROR: https://raw.githubusercontent.com/Mkalo/macro-maker/master/Matt.js
Downloaded file doesn't match hash specified in patch manifest! Possible causes:
   + Incorrect manifest specified by developer
   + NoPing (if you're using it) has a bug that can fuck up the download
 - lib/ahk.js
 - ERROR: https://raw.githubusercontent.com/Mkalo/macro-maker/master/lib/ahk.js
Downloaded file doesn't match hash specified in patch manifest! Possible causes:
   + Incorrect manifest specified by developer
   + NoPing (if you're using it) has a bug that can fuck up the download
 - ahk/input.ahk
 - ERROR: https://raw.githubusercontent.com/Mkalo/macro-maker/master/ahk/input.ahk
Downloaded file doesn't match hash specified in patch manifest! Possible causes:
   + Incorrect manifest specified by developer
   + NoPing (if you're using it) has a bug that can fuck up the download
[08:31:51.065] [update] Please go to https://github.com/Mkalo/macro-maker/issues and follow the given instructions or ask for help.
[08:31:51.066] [update] Alternatively, ask here: https://discord.gg/659YbNY

**Comment by Mkalo** [comment]
Should be fixed now.
