### ISSUE TITLE
onRelease

### ISSUE THREAD

**Issue by Big-Gay-Al** [Mkalo/macro-maker#2]
request

can you can an "onRelease" feature

to only trigger next skill once you stop holding a key. 

for example, holding Penetrating Arrow and after releasing it cast Sequential Fire

**Comment by Mkalo** [comment]
For that example, onCast with a delay would work better than an "onRelease", specially cause it would scale with attackspeed.

**Comment by Big-Gay-Al** [comment]
thanks so it would be like this?

```
            // Radiant Arrow
		"3": {
            enabled: true,
            key: "1",
            onCast: [
                { action: "keyTap", key: "6", delay: 2000 }
            ],
            repeater: true,
        },

```

**Comment by Mkalo** [comment]
If that delay is configured correctly, yeah.
