### ISSUE TITLE
Actions on Repeater?

### ISSUE THREAD

**Issue by itsPoipoi** [Mkalo/macro-maker#3]
Is it possible to use a repeater on skills/keys with MacroActions?
All I'm really trying to do is have repeater on, but only inCombat: true. Just want to have the key spammed but not when I'm typing, without having to toggle repeater manually.

**Comment by Mkalo** [comment]
No, the repeater is basically a simple ahk macro that is transpiled from your config. It doesn't exchange any information with the module after it's started.

The only way to make a repeater inside MacroActions would be using something like

```JavaScript
{
    enabled: true,
    key: "space",
    onPress: [
        { action: "keyRepeat", key: "space", duration: 500, interval: 25, inCombat: true }
    ]
}
```

But that means it won't repeat it until the key is released, instead it will spam it for 500ms on a 25ms interval. Making anything more complex than this would require another AHK layer to be executed to bind key_release events, and for now I think the configuration is already complex enough .
